
DROP TABLE IF EXISTS creative_cash_flow_notifiers CASCADE;
CREATE TABLE creative_cash_flow_notifiers (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  email text UNIQUE NOT NULL,
  enabled boolean NOT NULL DEFAULT true
);

ALTER TABLE creative_cash_flow_notifiers OWNER TO postgres;
ALTER TABLE creative_cash_flow_notifiers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin can view plaid creative_cash_flow_notifiers data" ON public.creative_cash_flow_notifiers
  FOR SELECT
  TO authenticated
  USING (is_admin(auth.uid()));

CREATE POLICY "Admin can insert plaid creative_cash_flow_notifiers" ON public.creative_cash_flow_notifiers
  FOR INSERT
  TO authenticated
  WITH CHECK (is_admin(auth.uid()));

CREATE POLICY "Admin can update plaid creative_cash_flow_notifiers data" ON public.creative_cash_flow_notifiers
  FOR UPDATE
  TO authenticated
  USING (is_admin(auth.uid()));

CREATE POLICY "Admin can delete plaid creative_cash_flow_notifiers" ON public.creative_cash_flow_notifiers
  FOR DELETE
  TO authenticated
  USING (is_admin(auth.uid()));
