CREATE TABLE global_plaid_filters (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  filter text UNIQUE NOT NULL,
  category category NOT NULL
);

ALTER TABLE global_plaid_filters OWNER TO postgres;
ALTER TABLE global_plaid_filters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view global plaid filters" ON global_plaid_filters
  FOR SELECT
  TO authenticated
  USING ((SELECT is_authenticated()));

CREATE POLICY "Admins can insert global plaid filters" ON global_plaid_filters
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT is_admin()));

CREATE POLICY "Admins can update global plaid filters" ON global_plaid_filters
  FOR UPDATE
  TO authenticated
  USING ((SELECT is_admin()));

CREATE POLICY "Admins can delete global plaid filters" ON global_plaid_filters
  FOR DELETE
  TO authenticated
  USING ((SELECT is_admin()));



CREATE OR REPLACE FUNCTION create_global_plaid_filter(
  _filter global_plaid_filters,
  override boolean
)
RETURNS global_plaid_filters AS $$
DECLARE
  new_filter global_plaid_filters;
BEGIN
  INSERT INTO global_plaid_filters (filter, category)
  VALUES (_filter.filter, _filter.category)
  RETURNING * INTO new_filter;

  -- Create a temporary table of transaction id's that match the filter, don't already
  -- have a user filter applied, and if the override flag is set, include transactions
  -- that have a global filter, otherwise, skip those
  CREATE TEMP TABLE temp_transactions AS
  SELECT pt.id
  FROM plaid_transactions pt
  JOIN plaid p ON p.item_id = pt.item_id
  WHERE
    pt.user_filter_id IS NULL
    AND CASE
      WHEN override = FALSE THEN pt.global_filter_id IS NULL
      ELSE TRUE
    END
    AND LOWER(pt.name) LIKE '%' || LOWER(_filter.filter) || '%';

  UPDATE plaid_transactions pt
  SET category = _filter.category,
    global_filter_id = new_filter.id
  FROM temp_transactions tt
  WHERE pt.id = tt.id;

  DROP TABLE temp_transactions;
  RETURN new_filter;
END;
$$ LANGUAGE plpgsql;

ALTER FUNCTION create_global_plaid_filter(
  _filter global_plaid_filters,
  override boolean
) OWNER TO postgres;



-- When a user filter is deleted, if the user selected a global filter to use,
-- then we will update the transactions to use the global filter instead.
CREATE OR REPLACE FUNCTION delete_global_plaid_filter(filter_id int, new_filter_id int DEFAULT NULL)
RETURNS VOID AS $$
DECLARE
  new_global_filter global_plaid_filters;
BEGIN
  IF new_filter_id IS NOT NULL THEN
    SELECT * FROM global_plaid_filters WHERE id = new_filter_id INTO new_global_filter;

    UPDATE plaid_transactions
    SET
      category = new_global_filter.category,
      global_filter_id = new_global_filter.id
    WHERE global_filter_id = filter_id;
  ELSE
    UPDATE plaid_transactions
    SET
      category = CASE
        WHEN amount < 0 THEN 'Money-In'::category
        ELSE 'Money-Out'::category
      END,
      global_filter_id = NULL
    WHERE global_filter_id = filter_id;
  END IF;

  DELETE FROM global_plaid_filters WHERE id = filter_id;
END;
$$ LANGUAGE plpgsql;

ALTER FUNCTION delete_global_plaid_filter(
  filter_id int,
  new_filter_id int
) OWNER TO postgres;



-- Only allow the "category" column to be updated and update the transactions
-- that use this filter is connected to
CREATE OR REPLACE FUNCTION update_global_plaid_filter()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.id <> OLD.id THEN
    RAISE EXCEPTION 'Updating "id" is not allowed';
  END IF;
  IF NEW.filter <> OLD.filter THEN
    RAISE EXCEPTION 'Updating "filter" is not allowed';
  END IF;

  UPDATE plaid_transactions
  SET category = NEW.category
  WHERE global_filter_id = NEW.id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

ALTER FUNCTION update_global_plaid_filter() OWNER TO postgres;

DROP TRIGGER IF EXISTS on_update_global_plaid_filter ON global_plaid_filters;
CREATE TRIGGER on_update_global_plaid_filter
  BEFORE UPDATE ON global_plaid_filters
    FOR EACH ROW
      EXECUTE FUNCTION update_global_plaid_filter();
