DROP TABLE IF EXISTS waa CASCADE;
CREATE TABLE waa (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date timestamp with time zone NOT NULL,
  amount numeric(12,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_waa_user_id ON waa(user_id);

ALTER TABLE waa OWNER TO postgres;
ALTER TABLE waa ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Can view own waa or is admin" ON waa
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id OR (SELECT is_admin()));

CREATE POLICY "Can insert new waa" ON waa
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Can update own debt data" ON waa
  FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Can delete own waa" ON waa
  FOR DELETE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);
