/**
 * user_plaid_filters table
 */

DROP TABLE IF EXISTS user_plaid_filters CASCADE;
CREATE TABLE user_plaid_filters (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES public.users(id),
  filter text UNIQUE NOT NULL,
  category category NOT NULL
);

ALTER TABLE user_plaid_filters OWNER TO postgres;
ALTER TABLE user_plaid_filters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own plaid filters" ON user_plaid_filters
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can insert own plaid filters" ON user_plaid_filters
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own plaid filters" ON user_plaid_filters
  FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own plaid filters" ON user_plaid_filters
  FOR DELETE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);



/**
 * global_plaid_filters table
 */

DROP TABLE IF EXISTS global_plaid_filters CASCADE;
CREATE TABLE global_plaid_filters (
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  filter text UNIQUE NOT NULL,
  category category NOT NULL
);

ALTER TABLE global_plaid_filters OWNER TO postgres;
ALTER TABLE global_plaid_filters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view global plaid filters" ON global_plaid_filters
  FOR SELECT
  TO authenticated
  USING ((SELECT is_admin()));

CREATE POLICY "Admins can insert global plaid filters" ON global_plaid_filters
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT is_admin()));

CREATE POLICY "Admins can update global plaid filters" ON global_plaid_filters
  FOR UPDATE
  TO authenticated
  USING ((SELECT is_admin()));

CREATE POLICY "Admins can delete global plaid filters" ON global_plaid_filters
  FOR DELETE
  TO authenticated
  USING ((SELECT is_admin()));



ALTER TABLE plaid_transactions
ADD COLUMN user_filter_id int REFERENCES user_plaid_filters(id),
ADD COLUMN global_filter_id int REFERENCES global_plaid_filters(id);
